name: Krane CI

on: [push]

jobs:
  ruby-tests:
    runs-on: ubuntu-latest

    name: "Tests - Ruby ${{ matrix.ruby }} with Kubernetes ${{ matrix.kubernetes_version }}"
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.1.2"
          - "3.0.4"
          - "2.7.6"
        kubernetes_version:
          - "1.24.6"
          - "1.23.12"
        include:
          - kubernetes_version: "1.24.6"
            kind_image: "kindest/node:v1.24.6@sha256:97e8d00bc37a7598a0b32d1fabd155a96355c49fa0d4d4790aab0f161bf31be1"
          - kubernetes_version: "1.23.12"
            kind_image: "kindest/node:v1.23.12@sha256:9402cf1330bbd3a0d097d2033fa489b2abe40d479cc5ef47d0b6a6960613148a"

    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Setup kubectl ${{ matrix.kubernetes_version }}
        run: |
          mkdir -p "${GITHUB_WORKSPACE}/bin"
          curl -o "${GITHUB_WORKSPACE}/bin/kubectl" -LO "https://dl.k8s.io/release/v${{ matrix.kubernetes_version }}/bin/linux/amd64/kubectl"
          chmod +x "${GITHUB_WORKSPACE}/bin/kubectl"
          echo "PATH=$GITHUB_WORKSPACE/bin:${PATH}" >> $GITHUB_ENV

      - name: Create kind cluster for ${{ matrix.kubernetes_version }}
        run: |
          kind create cluster --image=${{ matrix.kind_image }}

      - name: Run tests
        run: |
          bin/test
