name: Krane CI

on: [push]

jobs:
  ruby-tests:
    runs-on: ubuntu-latest

    name: "Tests - Ruby ${{ matrix.ruby }} with k8s ${{ matrix.kubernetes_version }}"
    strategy:
      fail-fast: false
      matrix:
        ruby:
        # Use unique Ruby versions, or GitHub gets confused when building the rest of the matrix
        - '3.1.2' # With k8s 1.24
        - '3.0.4' # With k8s 1.23
        - '2.7.6' # With k8s 1.22
        include:
        # Match kind images with chosen version https://github.com/kubernetes-sigs/kind/releases
        - ruby: '3.1.2'
          kind_version: 'v0.14.0'
          kubernetes_version: '1.24.0'
          kind_image: 'kindest/node:v1.24.0@sha256:0866296e693efe1fed79d5e6c7af8df71fc73ae45e3679af05342239cdc5bc8e'
        - ruby: '3.0.4'
          kind_version: 'v0.11.1'
          kubernetes_version: '1.23.0'
          kind_image: 'kindest/node:v1.23.0@sha256:49824ab1727c04e56a21a5d8372a402fcd32ea51ac96a2706a12af38934f81ac'
        - ruby: '2.7.6'
          kind_version: 'v0.11.1'
          kubernetes_version: '1.22.0'
          kind_image: 'kindest/node:v1.22.0@sha256:b8bda84bb3a190e6e028b1760d277454a72267a5454b57db34437c34a588d047'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Setup kubectl
        run: |
          mkdir -p "${GITHUB_WORKSPACE}/bin"
          curl -o "${GITHUB_WORKSPACE}/bin/kubectl" -LO "https://dl.k8s.io/release/v${{ matrix.kubernetes_version }}/bin/linux/amd64/kubectl"
          chmod +x "${GITHUB_WORKSPACE}/bin/kubectl"
          echo "PATH=$GITHUB_WORKSPACE/bin:${PATH}" >> $GITHUB_ENV

      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "${{ matrix.kind_version }}"
          image: "${{ matrix.kind_image }}"

      - name: Run tests
        run: |
          bin/test
